config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to:'blogs#index'

  resources :blogs, except: [:delete, :edit, :update]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

    def index
        @blogs = Blog.all.order(created_at: :desc)
    end

    def new
        @blogs = Blog.new
    end

    def create
        @blog = Blog.create(blog_filtered)
        @blog.save
        redirect_to '/'
    end

    def show
        @blog = Blog.find(params[:id])
    end

    private

    def blog_filtered
        params.require(:blog).permit([:title, :author, :content])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/index.html.erb
<div class="blog-container">

<% if @blogs.length == 0 %>
    <div>No blogs yet !</div>
<% else %>
    <% @blogs.each do |blog| %>
        <div class="blog-article">
            <h2 class="blog-title"><%= blog.title%></h2>
            <p class="blog-author">By <%= blog.author %></p>
            <p class="blog-content"><%= blog.content[0, 100] %></p>
            <a class="btn btn-info" href="<%= blogs_path + "/" + blog.id.to_s %>">See more</a>
        </div>
    <% end %>
<% end %>

</div>

app/views/blogs/new.html.erb
<%= form_for(@blogs) do |blog| %>
    <h1>Create your article on my blog :</h1>
    <div class="form-group">
        <label for="blog_author">Name of the author :</label>
        <%= blog.text_field :author %>
    </div>
    <div class="form-group">
        <label for="blog_title">Title of the article :</label>
        <%= blog.text_field :title %>
    </div>
    <div class="form-group">
        <label for="blog_content">What do you want to share with us ? :</label>
        <%= blog.text_area :content %>
    </div>
    <button type="submit" class="btn btn-info">Add</button>
<% end %>

app/views/blogs/show.html.erb
<h1 id="title"> <%= @blog.title %> </h1>
<p id="author"> By <%= @blog.author %></p>
<p> <%= @blog.content %> </p>
<%= @blog.created_at %>
<a href="<%= blogs_path %>" class="btn btn-info">Return to the blogs </a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav>
      <ul>
        <li><a href="<%= blogs_path %>">Blogs</a></li>
        <li><a href="<%= new_blog_path %>">Create</a></li>
      </ul>
    </nav>
    <div id="main">
      <%= yield %>
    </div>
  </body>
</html>